server:
  port: 8084
okta:
  oauth2:
    issuer: https://dev-689160.okta.com/oauth2/default
    client-id: 0oag1fguzK1kkw75F356
    client-secret: Sc36yTnNth2rT_2jaZ8XrXJNhcN_t3U2Xi0PO0uF
spring:
  thymeleaf:
    cache: false
